# Generated by Django 4.2.17 on 2025-03-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiDinamicPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrdataform',
            name='additionalImage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qrdataform',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qrdataform',
            name='businessName',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qrdataform',
            name='carouselImages',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='qrdataform',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='qrdataform',
            name='emailClient',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qrdataform',
            name='fontStyle',
            field=models.CharField(blank=True, default='Arial', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qrdataform',
            name='formData',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='qrdataform',
            name='generateQRCodeUrl',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='qrdataform',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qrdataform',
            name='logoShape',
            field=models.CharField(blank=True, default='square', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qrdataform',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='qrdataform',
            name='qrRef',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='qrdataform',
            name='socialMedia',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
