# Generated by Django 4.2.17 on 2025-09-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiDinamicPage', '0002_qrdataform_additionalimage_alter_qrdataform_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_base64',
            field=models.TextField(blank=True, help_text='Imagen en formato base64', null=True),
        ),
    ]
