# Generated by Django 4.2.17 on 2025-09-17 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiDinamicPage', '0003_profile_image_base64'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Título de la imagen', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Descripción de la imagen', null=True)),
                ('image_base64', models.TextField(help_text='Imagen en formato base64')),
                ('image_type', models.CharField(default='png', help_text='Tipo de imagen (png, jpg, jpeg, etc.)', max_length=50)),
                ('file_size', models.IntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True)),
                ('category', models.CharField(default='general', help_text='Categoría de la imagen', max_length=100)),
                ('is_public', models.BooleanField(default=True, help_text='Si la imagen es pública o privada')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags para categorizar la imagen', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'apiDinamicPage_userimage',
                'ordering': ['-created_at'],
            },
        ),
    ]
