# Generated by Django 4.2.17 on 2025-09-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiDinamicPage', '0004_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Archivo de imagen', null=True, upload_to='user_images'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image_base64',
            field=models.TextField(blank=True, help_text='Imagen en formato base64', null=True),
        ),
    ]
