# Generated by Django 4.2.17 on 2025-12-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiDinamicPage', '0005_userimage_image_alter_userimage_image_base64'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la URL (ej: template, user, etc.)', max_length=100, unique=True)),
                ('url', models.CharField(help_text='URL completa de la API', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'apiDinamicPage_apiurl',
                'ordering': ['name'],
            },
        ),
    ]
