# Generated by Django 4.2.17 on 2026-01-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiDinamicPage', '0006_apiurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='VCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Título de la tarjeta de presentación', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Descripción de la tarjeta', null=True)),
                ('image_base64', models.TextField(blank=True, help_text='Imagen en formato base64', null=True)),
                ('vcard_data', models.JSONField(blank=True, default=dict, help_text='Datos completos del vCard incluyendo información personal y diseño', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'apiDinamicPage_vcard',
                'ordering': ['-created_at'],
            },
        ),
    ]
